#! /bin/sh

pkill sxhkd
sxhkd &

bspc monitor HDMI-A-0 -d I II III
bspc monitor HDMI-A-1 -d IV V VI

bspc config border_width        6
bspc config window_gap          32

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc rule -r *:*

feh --bg-scale ~/Pictures/alenabg2.jpg
xsetroot -cursor_name left_ptr
~/.config/polybar/launch.sh &
compton &

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
